# set this to the location where Kochiku web is running
kochiku_web_host: "kochiku.corp.squareup.com"

# Change this if you want to run Redis on a different machine than the build master
# This needs to be the same as the Redis instance that the Kochiku application uses
redis_host: "kochiku.corp.squareup.com"

# Change this to the hostnames for the kochiku worker boxes that you want to deploy to
worker_hosts:
  - macbuild01.sfo.squareup.com
  - macbuild02.sfo.squareup.com
  - macbuild03.sfo.squareup.com
  - macbuild04.sfo.squareup.com
  - macbuild05.sfo.squareup.com
  - macbuild06.sfo.squareup.com
  - macbuild07.sfo.squareup.com
  - macbuild08.sfo.squareup.com
  - macbuild09.sfo.squareup.com
  - macbuild10.sfo.squareup.com
  - macbuild11.sfo.squareup.com
  - macbuild12.sfo.squareup.com
  - macbuild13.sfo.squareup.com
  - macbuild14.sfo.squareup.com
  - macbuild15.sfo.squareup.com
  - macbuild16.sfo.squareup.com
  - macbuild17.sfo.squareup.com
  - macbuild18.sfo.squareup.com
  - macbuild19.sfo.squareup.com
  - macbuild20.sfo.squareup.com
  - macbuild21.sfo.squareup.com
  - macbuild22.sfo.squareup.com
  - work81.ec2.squareup.com
  - work98.ec2.squareup.com
  - work86.ec2.squareup.com
  - work171.ec2.squareup.com
  - work215.ec2.squareup.com
  - work246.ec2.squareup.com
  - work133.ec2.squareup.com
  - work170.ec2.squareup.com
  - work181.ec2.squareup.com
  - work82.ec2.squareup.com
  - work68.ec2.squareup.com
  - work244.ec2.squareup.com
  - work104.ec2.squareup.com
  - work140.ec2.squareup.com
  - work5.ec2.squareup.com
  - work56.ec2.squareup.com
  - work174.ec2.squareup.com
  - work187.ec2.squareup.com
  - work53.ec2.squareup.com
  - work80.ec2.squareup.com
  - work152.ec2.squareup.com
  - work242.ec2.squareup.com
  - work194.ec2.squareup.com
  - work226.ec2.squareup.com
  - work38.ec2.squareup.com
  - work234.ec2.squareup.com
  - work173.ec2.squareup.com
  - work141.ec2.squareup.com
  - work102.ec2.squareup.com
  - work107.ec2.squareup.com
  - work17.ec2.squareup.com
  - work106.ec2.squareup.com
  - work177.ec2.squareup.com
  - work197.ec2.squareup.com
  - work182.ec2.squareup.com
  - work87.ec2.squareup.com
  - work69.ec2.squareup.com
  - work237.ec2.squareup.com
  - work219.ec2.squareup.com
  - work90.ec2.squareup.com
  - work129.ec2.squareup.com
  - work99.ec2.squareup.com
  - work230.ec2.squareup.com
  - work229.ec2.squareup.com
  - work126.ec2.squareup.com
  - work241.ec2.squareup.com
  - work243.ec2.squareup.com
  - work203.ec2.squareup.com
  - work189.ec2.squareup.com
  - work11.ec2.squareup.com
  - work23.ec2.squareup.com
  - work75.ec2.squareup.com
  - work36.ec2.squareup.com
  - work202.ec2.squareup.com
  - work44.ec2.squareup.com
  - work39.ec2.squareup.com
  - work231.ec2.squareup.com
  - work84.ec2.squareup.com
  - work6.ec2.squareup.com
  - work46.ec2.squareup.com
  - work225.ec2.squareup.com
  - work205.ec2.squareup.com
  - work240.ec2.squareup.com
  - work186.ec2.squareup.com
  - work79.ec2.squareup.com
  - work245.ec2.squareup.com
  - work59.ec2.squareup.com
  - work248.ec2.squareup.com
  - work153.ec2.squareup.com
  - work14.ec2.squareup.com
  - work111.ec2.squareup.com
  - work13.ec2.squareup.com
  - work176.ec2.squareup.com
  - work19.ec2.squareup.com
  - work163.ec2.squareup.com
  - work137.ec2.squareup.com
  - work77.ec2.squareup.com
  - work66.ec2.squareup.com
  - work201.ec2.squareup.com
  - work254.ec2.squareup.com
  - work156.ec2.squareup.com
  - work4.ec2.squareup.com
  - work73.ec2.squareup.com
  - work238.ec2.squareup.com
  - work120.ec2.squareup.com
  - work224.ec2.squareup.com
  - work51.ec2.squareup.com
  - work190.ec2.squareup.com
  - work110.ec2.squareup.com
  - work210.ec2.squareup.com
  - work214.ec2.squareup.com
  - work48.ec2.squareup.com
  - work167.ec2.squareup.com
  - work169.ec2.squareup.com
  - work175.ec2.squareup.com
  - work16.ec2.squareup.com
  - work249.ec2.squareup.com
  - work25.ec2.squareup.com
  - work72.ec2.squareup.com
  - work178.ec2.squareup.com
  - work85.ec2.squareup.com
  - work150.ec2.squareup.com
  - work218.ec2.squareup.com
  - work250.ec2.squareup.com
  - work196.ec2.squareup.com
  - work18.ec2.squareup.com
  - work101.ec2.squareup.com
  - work236.ec2.squareup.com
  - work15.ec2.squareup.com
  - work168.ec2.squareup.com
  - work20.ec2.squareup.com
  - work88.ec2.squareup.com
  - work108.ec2.squareup.com
  - work34.ec2.squareup.com
  - work64.ec2.squareup.com
  - work37.ec2.squareup.com
  - work24.ec2.squareup.com
  - work28.ec2.squareup.com
  - work211.ec2.squareup.com
  - work130.ec2.squareup.com
  - work223.ec2.squareup.com
  - work159.ec2.squareup.com
  - work112.ec2.squareup.com
  - work251.ec2.squareup.com
  - work83.ec2.squareup.com
  - work12.ec2.squareup.com
  - work232.ec2.squareup.com
  - work204.ec2.squareup.com
  - work63.ec2.squareup.com
  - work67.ec2.squareup.com
