# set this to the location where Kochiku web is running
kochiku_web_host: "kochiku.corp.squareup.com"

# Change this if you want to run Redis on a different machine than the build master
# This needs to be the same as the Redis instance that the Kochiku application uses
redis_host: "kochiku.corp.squareup.com"

# Change this to the hostnames for the kochiku worker boxes that you want to deploy to
worker_hosts:
  - macbuild01.hq.squareup.com
  - macbuild02.hq.squareup.com
  - macbuild03.hq.squareup.com
  - macbuild04.hq.squareup.com
  - macbuild05.hq.squareup.com
  - macbuild06.hq.squareup.com
  - macbuild07.hq.squareup.com
  - macbuild08.hq.squareup.com
  - macbuild09.hq.squareup.com
  - macbuild10.hq.squareup.com
  - macbuild11.hq.squareup.com
  - macbuild12.hq.squareup.com
  - macbuild13.hq.squareup.com
  - macbuild14.hq.squareup.com
  - macbuild15.corp.squareup.com
  - macbuild16.corp.squareup.com
  - macbuild17.corp.squareup.com
  - macbuild18.corp.squareup.com
  - macbuild19.corp.squareup.com
  - macbuild20.corp.squareup.com
  - macbuild21.corp.squareup.com
  - macbuild22.corp.squareup.com
  - macbuild22.hq.squareup.com

