# set this to the location where Kochiku web is running
kochiku_web_host: "kochiku.corp.squareup.com"

# Change this if you want to run Redis on a different machine than the build master
# This needs to be the same as the Redis instance that the Kochiku application uses
redis_host: "kochiku.corp.squareup.com"

# Change this to the hostnames for the kochiku worker boxes that you want to deploy to
worker_hosts:
  - macbuild01.corp.squareup.com
  - macbuild02.corp.squareup.com
  - macbuild03.corp.squareup.com
  - macbuild04.corp.squareup.com
  - macbuild05.corp.squareup.com
  - macbuild06.corp.squareup.com
  - macbuild07.corp.squareup.com
  - macbuild08.corp.squareup.com
  - macbuild09.corp.squareup.com
  - macbuild10.corp.squareup.com
  - macbuild11.corp.squareup.com
  - macbuild12.corp.squareup.com
  - macbuild13.corp.squareup.com
  - macbuild14.corp.squareup.com
  - macbuild15.corp.squareup.com
  - macbuild16.corp.squareup.com
  - macbuild17.corp.squareup.com
  - macbuild18.corp.squareup.com
  - macbuild19.corp.squareup.com
  - macbuild20.corp.squareup.com
  - macbuild21.corp.squareup.com
  - macbuild22.corp.squareup.com

