# set this to the location where Kochiku web is running
kochiku_web_host: "kochiku-new.corp.squareup.com"
kochiku_web_protocol: "https"

# Change this if you want to run Redis on a different machine than the build master
# This needs to be the same as the Redis instance that the Kochiku application uses
redis_host: "kochiku-a-01.corp.squareup.com"

# Change this to the hostnames for the kochiku worker boxes that you want to deploy to
worker_hosts:
  - macbuild01.hq.squareup.com
  - macbuild02.hq.squareup.com
  - macbuild03.hq.squareup.com
  - macbuild04.hq.squareup.com
  - macbuild05.hq.squareup.com
  - macbuild06.hq.squareup.com
  - macbuild07.hq.squareup.com
  - macbuild08.hq.squareup.com
  - macbuild09.hq.squareup.com
  - macbuild10.hq.squareup.com
  - macbuild11.hq.squareup.com
  - macbuild12.hq.squareup.com
  - macbuild13.hq.squareup.com
  - macbuild14.hq.squareup.com
  - macbuild15.hq.squareup.com
  - macbuild16.hq.squareup.com
  - macbuild17.hq.squareup.com
  - macbuild18.hq.squareup.com
  - macbuild19.hq.squareup.com

